const config = {
    routes: {
        home: "/",
        products: "/products",
        productDetail: "/products/:id",
        blog: "/blog",
        blogDetail: "/blog/:slug",
        blogTag: "/blog/tag/:tagName",
        learning: "/learning-paths",
        learningItem: "/learning-paths/:nameCourse",
        notFound: "*",
        authenticationApp: "/authenticationApp",
        register: "/register",
        login: "/login",
        forgotPassWord: "/forgot-passWord",
        settingApp: "/setting/p/:username",
        setting: "/setting",
        aboutUs: "/about-us",
        contactUs: "/contact-us",
        terms: "/terms",
        paymentSuccess: "/payment/success",
        paymentCancel: "/payment/cancel",
        privacy: "/privacy",
        profile: "/profile/:username",
        writePost: "/new-post",
        postEdit: "/post/edit",
        myPost: "/me/posts",
        myPostPublished: "/me/posts/published",
        myBookmark: "/me/bookmark",
        courseDetail: "/courses/:slug",
        courseLessonPage: "/learning/:slug",
        verifyEmail: "/verify-email",
        resendEmail: "/resend-email",
        searchResults: "/search-results",
        // admin routes
        admin: "/admin",
        adminLogin: "/admin/login",
        adminUsers: "/admin/users",
        adminCourses: "/admin/courses",
        adminPosts: "/admin/posts",
        adminComments: "/admin/comments",
        adminTopics: "/admin/topics",
        adminInstructors: "/admin/instructors",
        adminSettings: "/admin/settings",
        adminStatistics: "/admin/statistics",
        adminLesson: "/admin/lessons",
        adminTrack: "/admin/tracks",
        adminLearningPaths: "/admin/learning-paths",
        adminSlideshow: "/admin/slideshow",
    },
};

export default config;
